echo " Arguments Total : $# "
echo " script name : $0 "
echo " script 1st argement : $1 "
echo " script 2nd argument : $2 "
echo " script 3rd argument : $3 "
echo " list of all aruments : * $* "
echo " list of all arguments : @ $@ "
echo " pid of shell : $$ "
